version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: akshat
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: LeapWallet
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - .db:/data
    restart: always
    entrypoint: redis-server --appendonly yes

  leapawallet:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: akshat
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: LeapWallet
      DB_PASSWORD: 12345
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 12345
      REDIS_URL: "redis://redis:6379"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
